document.write("<div id='cssmenu'>");
document.write("<ul>");
   document.write("<li class='active'><a href='index.html'><span>Home</span></a></li>");
   document.write("<li class='has-sub last'><a href='#'><span>Servizi</span></a>");
      document.write("<ul>");
         document.write("<li class='has-sub'><a href='parte1.html'><span>Parte1</span></a>");
			document.write("<li class='has-sub'><a href='parte2.html'><span>Parte2</span></a>");
            document.write("</ul>");
   document.write("</li>");
document.write("</ul>");
document.write("</div>");