document.write("<div id='cssmenu'>");
document.write("<ul>");
 document.write("  <li><a href='index.html'><span>Home</span></a></li>");
 document.write("  <li class='has-sub '><a href='#'><span>Componenti</span></a>");
  document.write("    <ul>");
  document.write("       <li class='has-sub '><a href='Modem.html'><span>Modem</span></a>");
   document.write("         <ul>");
  document.write("             <li><a href='modemserve.html'><span>A cosa serve?</span></a></li>");
    document.write("           <li><a href='modemfatto.html'><span>Come è fatto?</span></a></li>");
    document.write("        </ul>");
    document.write("     </li>");
   document.write("      <li class='has-sub '><a href='Firewall.html'><span>Firewall</span></a>");
    document.write("        <ul>");
   document.write("            <li><a href='firewallserve.html'><span>A cosa serve?</span></a></li>");
      document.write("         <li><a href='firewallfatto.html'><span>Come è fatto?</span></a></li>");
    document.write("        </ul>");
    document.write("     </li>");
	document.write("	 <li class='has-sub '><a href='Proxy.html'><span>Proxy</span></a>");
    document.write("        <ul>");
     document.write("         <li><a href='proxyserve.html'><span>A cosa serve?</span></a></li>");
     document.write("          <li><a href='proxyfatto.html'><span>Come è fatto?</span></a></li>");
     document.write("       </ul>");
	document.write("		</li>");
	document.write("		<li class='has-sub '><a href='Router.html'><span>Router</span></a>");
     document.write("       <ul>");
     document.write("          <li><a href='routerserve.html'><span>A cosa serve?</span></a></li>");
    document.write("           <li><a href='routerfatto.html'><span>Come è fatto?</span></a></li>");
        document.write("    </ul>");
		document.write("	</li>");
	document.write("	 <li class='has-sub '><a href='Switch.html'><span>Switch</span></a>");
    document.write("        <ul>");
    document.write("           <li><a href='switchserve.html'><span>A cosa serve?</span></a></li>");
     document.write("          <li><a href='switchfatto.html'><span>Come è fatto?</span></a></li>");
   document.write("         </ul>");
   document.write("   </ul>");
  document.write(" </li>");
document.write("   <li><a href='#'><span>Contact</span></a></li>");
 document.write("  <li><a href='#'><span>About</span></a></li>");
document.write("</ul>");
document.write("</div>");