document.write("<div id='cssmenu'>");
document.write("<ul>");
document.write("   <li><a href='index.html'><span>Home</span></a></li>");
document.write("  <li class='has-sub '><a href='#'><span>componenti</span></a>");
document.write("      <ul>");
document.write("         <li class='has-sub '><a href='modem.html'><span>modem</span></a>");
document.write("            <ul>");
document.write("               <li><a href='modem cosa.html'><span>cosa fa</span></a></li>");
document.write("           </ul>");
document.write("        </li>");
document.write("         <li class='has-sub '><a href='proxy.html'><span>proxy</span></a>");
document.write("            <ul>");
document.write("               <li><a href='proxy cosa.html'><span>cosa fa</span></a></li>");
document.write("            </ul>");
document.write("         </li>");
document.write("          <li class='has-sub '><a href='firewall.html'>firewall<span></span></a>");
document.write("            <ul>");
document.write("			 <li><a href='firewall cosa.html'><span></span>cosa fa </a></li>");
document.write("			 </ul>");
document.write("       </li>");
document.write("      <li class='has-sub '><a href='router.html'><span>router</span></a> ");
document.write("       <ul>");
document.write("               <li><a href='router cosa.html'><span>cosa fa</span></a></li>");
document.write("			    </ul>");
document.write("		    </li>");
document.write("      <li class='has-sub '><a href='switch.html'><span>switch</span></a> ");
document.write("       <ul>");
document.write("               <li><a href='switch cosa.html'><span>cosa fa</span></a></li>");
document.write("			    </ul>");
document.write("		    </li>");
document.write("      <li class='has-sub '><a href='access point.html'><span>access point</span></a> ");
document.write("       <ul>");
document.write("               <li><a href='access point cosa.html'><span>cosa fa</span></a></li>");
document.write("			    </ul>");
document.write("		    </li>");
document.write("      <li class='has-sub '><a href='gateway.html'><span>gateway</span></a> ");
document.write("       <ul>");
document.write("               <li><a href='gateway cosa.html'><span>cosa fa</span></a></li>");
document.write("			    </ul>");
document.write("		    </li>");
document.write("			<li class='has-sub '><a href='hub.html'><span>hub</span></a> ");
document.write("            <ul>");
document.write("			<li><a href='hub cosa.html'><span>cosa fa</span></a></li>");
document.write("			</ul>");
document.write("			</li>");
document.write("			</ul>");
document.write("         </li> ");
document.write("   <li><a href='#'><span>About</span></a></li>");
document.write("   <li><a href='#'><span>Contact</span></a></li>");
document.write("</ul>");
document.write("</div>");