document.write("<div id='cssmenu'>");
document.write("<ul>");
 document.write("  <li><a href='index.html'><span>Home</span></a></li>");
  document.write(" <li class='has-sub '><a href='#'><span>componenti</span></a>");
  document.write("    <ul>");
document.write("         <li class='has-sub '><a href='modem.html'><span>Modem</span></a>");
 document.write("           <ul>");
 document.write("              <li><a href='modem cosa.html'><span>cosa fa</span></a></li>");
 document.write("           </ul>");
 document.write("        </li>");
 document.write("         <li class='has-sub '><a href='FIREWALL.html'><span>Firewall</span></a>");
 document.write("           <ul>");
 document.write("              <li><a href='modem cosa.html'><span>cosa fa</span></a></li>");
 document.write("           </ul>");
 document.write("         <li class='has-sub '><a href='GATEWAY.html'><span>Gateway</span></a>");
 document.write("           <ul>");
 document.write("              <li><a href='modem cosa.html'><span>cosa fa</span></a></li>");
 document.write("           </ul>");
 document.write("        </li>");
  document.write("         <li class='has-sub '><a href='access.html'><span>Access Point</span></a>");
 document.write("           <ul>");
 document.write("              <li><a href='modem cosa.html'><span>cosa fa</span></a></li>");
 document.write("           </ul>");
 document.write("        </li>");
 document.write("        <li class='has-sub '><a href='proxy.html'><span>Proxy</span></a>");
 document.write("           <ul>");
  document.write("             <li><a href='proxy cosa.html'><span>cosa fa</span></a></li>");
  document.write("          </ul>");
  document.write("       </li>");
document.write("		  <ul>");
  document.write("         <li><a href='#'><span>cosa fa</span></a></li>");
document.write("            </ul>");
 document.write("        </li>");
document.write("         <li class='has-sub '><a href='hub.html'><span>Hub</span></a>");
 document.write("           <ul>");
  document.write("             <li><a href='hub cosa.html'><span>cosa fa</span></a></li>");
 document.write("           </ul>");
  document.write("       </li>");
document.write("		<ul>");
  document.write("             <li><a href='#'><span>cosa fa</span></a></li>");
 document.write("           </ul>");
 document.write("        </li>");
 document.write("        <li class='has-sub '><a href='router.html'><span>Router</span></a>");
  document.write("          <ul>");
   document.write("            <li><a href='router cosa.html'><span>cosa fa</span></a></li>");
 document.write("           </ul>");
 document.write("        </li>");
document.write("		 		             <ul>");
document.write("               <li><a href='#'><span>cosa fa</span></a></li>");          
document.write("            </ul>");
 document.write("        </li>");
 document.write("        <li class='has-sub '><a href='switch.html'><span>Switch</span></a>");
 document.write("           <ul>");
 document.write("              <li><a href='switch cosa.html'><span>cosa fa</span></a></li>");
 document.write("           </ul>");         
  document.write("       </li>");
 document.write("     </ul>");
  document.write(" </li>");
 document.write("  <li><a href='#'><span>About</span></a></li>");
 document.write("  <li><a href='#'><span>Contact</span></a></li>");
document.write("</ul>");
document.write("</div>");