document.write("<div id='cssmenu'> ");
document.write("<ul>");
document.write("  <li><a href='index.html'><span>Home</span></a></li>");
document.write("  <li class='has-sub '><a href='#'><span>Componenti</span></a>");
document.write("     <ul>");
document.write("       <li class='has-sub '><a href='modem.html'><span>Modem</span></a>");
document.write("		 <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("          </ul>");
document.write("		 </li>");
document.write("        <li class='has-sub '><a href='router.html'><span>router</span></a>");
document.write("	  <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("		  </li>");
document.write("         <li class='has-sub '><a href='proxy.html'><span>Proxy</span></a>");
document.write("            <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("        </li>");
document.write("		 <li class='has-sub '><a href='Hub.html'><span>Hub</span></a>");
document.write("		 <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("		</li>");
document.write("		 <li class='has-sub '><a href='firewall.html'><span>Firewall</span></a>");
document.write("		 <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("		</li>");
document.write("		 <li class='has-sub '><a href='access point.html'><span>Access Point</span></a>");
document.write("		 <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("		</li>");
document.write("		 <li class='has-sub '><a href='Gateway.html'><span>Gateway</span></a>");
document.write("		 <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("		</li>");
document.write("    <li class='has-sub '><a href='switch.html'><span>switch</span></a>");
document.write("    <ul>");
document.write("	 <li><a href='#'><span>Come Funziona<span></a></li>  ");             
document.write("      </ul>");
document.write("     </li>");
document.write("</ul>");
document.write("  <li><a href='#'><span>About</span></a></li>");
document.write("  <li><a href='#'><span>Contact</span></a></li>");
document.write("</ul>");
document.write("</div>");