document.write("<div id='cssmenu'>");
document.write("<ul>");
   document.write("<li><a href='index.html'><span>Home</span></a></li>");
   document.write("<li class='has-sub '><a href=''><span>Componenti</span></a>");
      document.write("<ul>");
         document.write("<li class='has-sub '><a href='modem.html'><span>Modem</span></a>");
            document.write("<ul>");
               document.write("<li><a href='modemServe.html'><span>A cosa serve</span></a></li>");
              document.write ("<li><a href='modemFatto.html'><span>Come e' fatto</span></a></li>");
            document.write("</ul>");
        document.write(" </li>");
        document.write ("<li class='has-sub '><a href='proxy.html'><span>Proxy</span></a>");
          document.write  ("<ul>");
              document.write(" <li><a href='proxyServe.html'><span>A cosa serve</span></a></li>");
             document.write  ("<li><a href='proxyFatto.html  '><span>Come e' fatto</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
		       document.write ("  <li class='has-sub '><a href='Firewall.html'><span>Firewall</span></a>");
          document.write  ("<ul>");
           document.write   (" <li><a href='FirewallServe.html'><span>A cosa serve</span></a></li>");
           document.write   (" <li><a href=' FirewallFatto.html  '><span>Come e' fatto</span></a></li>");
          document.write (" </ul>");
       document.write  ("</li>");
		document.write ("<li class='has-sub '><a href='Router.html'><span>Router</span></a>");
         document.write   ("<ul>");
            document.write(" <li><a href='RouterServe.html'><span>A cosa serve</span></a></li>");
              document.write ("<li><a href=' RouterFatto.html  '><span>Come e' fatto</span></a></li>");
           document.write ("</ul>");
			document.write("<li class='has-sub '><a href='Switch.html'><span>Switch</span></a>");
           document.write(" <ul>");
              document.write(" <li><a href='SwitchServe.html'><span>A cosa serve</span></a></li>");
             document.write (" <li><a href=' SwitchFatto.html  '><span>Come e' fatto</span></a></li>");
           document.write ("</ul>");
		   document.write("<li class='has-sub '><a href='Access Point.html'><span>Access Point</span></a>");
		              document.write(" <ul>");
              document.write(" <li><a href='PointServe.html'><span>A cosa serve</span></a></li>");
             document.write (" <li><a href=' PointFatto.html  '><span>Come e' fatto</span></a></li>");
           document.write ("</ul>");
		   		   document.write("<li class='has-sub '><a href='gateway.html'><span>Gateway</span></a>");
		              document.write(" <ul>");
              document.write(" <li><a href='gatewayServe.html'><span>A cosa serve</span></a></li>");
             document.write (" <li><a href=' gatewayFatto.html  '><span>Come e' fatto</span></a></li>");
           document.write ("</ul>");
		   			
   document.write ("  </ul>");
  document.write ("</li>");
  document.write ("<li><a href='#'><span>About</span></a></li>");
 document.write  ("<li><a href='#'><span>Contact</span></a></li>");
document.write("</ul>");
document.write("</div>");