document.write("<div id='cssmenu'> ");
document.write("<ul>");
document.write("  <li><a href='Cloud.html'><span>Home</span></a></li>");
document.write("  <li class='has-sub '><a href='#'><span>I servizi di cloud</span></a>");
document.write("     <ul>");
document.write("       <li class='has-sub '><a href='dropbox.html'><span>Dropbox</span></a>");
document.write("		 <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("          </ul>");
document.write("		 </li>");
document.write("        <li class='has-sub '><a href='Box.html'><span>Box</span></a>");
document.write("	  <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("		  </li>");
document.write("         <li class='has-sub '><a href='Google drive.html'><span>Google drive</span></a>");
document.write("            <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("        </li>");
document.write("		 <li class='has-sub '><a href='SkyDrive.html'><span>SkyDrive</span></a>");
document.write("		 <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("		</li>");
document.write("		 <li class='has-sub '><a href='TeamDrive.html'><span>TeamDrive</span></a>");
document.write("		 <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("		</li>");
document.write("		 <li class='has-sub '><a href='Cloudme.html'><span>Cloudme</span></a>");
document.write("		 <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("		</li>");
document.write("		 <li class='has-sub '><a href='Amazon cloud drive.html'><span>Amazon cloud drive</span></a>");
document.write("		 <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("		</li>");
document.write("		 <li class='has-sub '><a href='surdoc.html'><span>surdoc</span></a>");
document.write("		 <ul>");
document.write("              <li><a href='#'><span>Come Funziona</span></a></li>");
document.write("           </ul>");
document.write("		</li>");
document.write("</ul>");
document.write("  <li><a href='#'><span>About</span></a></li>");
document.write("  <li><a href='#'><span>Contact</span></a></li>");
document.write("</ul>");
document.write("</div>");