document.write("<div id='cssmenu'> ");
document.write("<ul>");
document.write("<li><a href='/Galdus'><span>Home</span></a></li> ");
document.write("<li><a href='creaDB.html'><span>crea il database</span></a> </li> ");
document.write("<li><a href='creaTabella.html'><span>creare la tabella</span></a> </li>  ");
document.write("<li class='has-sub'><a href='inserisci.html'><span>Inserimento dati</span></a> ");
document.write("    <ul>");
document.write("       <li><a href='insertData.html'><span>Script inserimento</span></a></li>");
document.write("    </ul>");
document.write("</li> ");
document.write("<li class='has-sub'><a href='showdataDelete.php'><span>Visualizzazione dati</span></a> ");
document.write("    <ul>");
document.write("       <li><a href='showDataDelete.html'><span>Script visualizzazione</span></a></li>");
document.write("       <li><a href='deleteData.html'><span>Script eliminazione</span></a></li>");
document.write("    </ul>");
document.write("</li> ");
document.write(" <li class='has-sub'><a href='showdataUpdate.php'><span>Aggiornamento dati</span></a>");
document.write("    <ul>");
document.write("       <li><a href='showDataUpdate.html'><span>Script visualizzazione</span></a></li>");
document.write("       <li><a href='updateData.html'><span>Script aggiornamento</span></a></li>");
document.write("    </ul>");
document.write("</li> ");
document.write(" <li class='has-sub'><a href='cancella.html'><span>Cancellazione dati</span></a>");
document.write("    <ul>");
document.write("       <li><a href='deleteData.html'><span>Script cancellazione</span></a></li>");
document.write("    </ul>");
document.write("</li> ");
document.write("</ul> ");
document.write("</div>  ");