document.write("<div id='cssmenu'>");
document.write("<ul>");
document.write("   <li><a href='cloud.html'><span>Home</span></a></li>");
document.write("   <li class='has-sub '><a href='#'><span>I Servizi Di Cloud</span></a>");
document.write("      <ul>");
document.write("         <li class='has-sub '><a href='dropbox.html'><span>dropbox</span></a>");
document.write("            <ul>");
document.write("               <li><a href='dropbox.html'><span>cosa fa</span></a></li>");
document.write("            </ul>");
document.write("         </li>");
document.write("         <li class='has-sub '><a href='box.html'><span>box</span></a>");
document.write("            <ul>");
document.write("               <li><a href='box.html'><span>cosa fa</span></a></li>");
document.write("            </ul>");
document.write("         </li>");
document.write("           <li class='has-sub '><a href='google drive.html'>google drive<span></span></a>");
document.write("            <ul>");
document.write("			 <li><a href='google drive.html'><span></span>cosa fa </a></li>");
document.write("			 </ul>");
document.write("         </li>");
document.write("         <li class='has-sub '><a href='skydrive.html'><span>skydrive</span></a> ");
document.write("            <ul>");
document.write("               <li><a href='skydrive.html'><span>cosa fa</span></a></li>");
document.write("			    </ul>");
document.write("		    </li>");
document.write("         <li class='has-sub '><a href='teamdrive.html'><span>teamdrive</span></a> ");
document.write("            <ul>");
document.write("               <li><a href='teamdrive.html'><span>cosa fa</span></a></li>");
document.write("			</ul>");
document.write("		  </li>");
document.write("         <li class='has-sub '><a href='cloudme.html'><span>cloudme</span></a> ");
document.write("            <ul>");
document.write("               <li><a href='cloudme.html'><span>cosa fa</span></a></li>");
document.write("			</ul>");
document.write("		  </li>");
document.write("         <li class='has-sub '><a href='surdoc.html'><span>surdoc</span></a> ");
document.write("            <ul>");
document.write("               <li><a href='surdoc.html'><span>cosa fa</span></a></li>");
document.write("			</ul>");
document.write("		  </li>");
document.write("			</ul>");
document.write("		  </li>");
document.write("		 ");
document.write("   <li><a href='#'><span>About</span></a></li>");
document.write("   <li><a href='#'><span>Contact</span></a></li>");
document.write("</ul>");
document.write("</div>");