
document.write("<div id='cssmenu'>")
document.write("<ul>");
   document.write("<li><a href='index.html'><span>Home</span></a></li>");
   document.write("<li class='has-sub '><a href='#'><span>Componenti</span></a>");
      document.write("<ul>");
         document.write("<li class='has-sub '><a href='modem.html'><span>Modem</span></a>");
             document.write("<ul>");
               document.write("<li><a href='modemServe.html'><span>A cosa serve</span></a></li>");
               document.write("<li><a href='modemFatto.html'><span>Come è fatto</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
         document.write("<li class='has-sub '><a href='Router.html'><span>Router</span></a>");
            document.write("<ul>");
               document.write("<li><a href='RouterServe.html'><span>A cosa serve</span></a></li>");
               document.write("<li><a href='RouterFatto.html'><span>Come è fatto</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
		 document.write("<li class='has-sub '><a href='Firewalle.html'><span>Firewalle</span></a>");
            document.write("<ul>");
               document.write("<li><a href='firewalleServe.html'><span>A cosa serve</span></a></li>");
               document.write("<li><a href='firewalleFatto.html'><span>Come è fatto</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
		 document.write("<li class='has-sub '><a href='Proxy.html'><span>proxy</span></a>");
            document.write("<ul>");
              document.write("<li><a href='proxyServe.html'><span>A cosa serve</span></a></li>");
               document.write("<li><a href='proxyFatto.html'><span>Come è fatto</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
		 document.write("<li class='has-sub '><a href='switch.html'><span>switch</span></a>");
            document.write("<ul>");
             document.write("<li><a href='switchServe.html'><span>A cosa serve</span></a></li>");
               document.write("<li><a href='switchFatto.html'><span>Come è fatto</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
		 document.write("<li class='has-sub '><a href='acces.html'><span>Access Point</span></a>");
            document.write("<ul>");
               document.write("<li><a href='accesServe.html'><span>A cosa serve</span></a></li>");
               document.write("<li><a href='accesFatto.html'><span>Come è fatto</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
		 document.write("<li class='has-sub '><a href='hub.html'><span>Hub</span></a>");
            document.write("<ul>");
               document.write("<li><a href='hubServe.html'><span>A cosa serve</span></a></li>");
               document.write("<li><a href='hubFatto.html'><span>Come è fatto</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
      document.write("</ul>");
   document.write("</li>");
   document.write("<li><a href='#'><span>About</span></a></li>");
   document.write("<li><a href='#'><span>Contact</span></a></li>");
document.write("</ul>");
document.write("</div>");

