document.write("<div id='cssmenu'>");
document.write("<ul>");
   document.write("<li><a href='Componenti reti.html'><span>Home</span></a></li>");
   document.write("<li class='has-sub '><a href='#'><span>Componenti</span></a>");
      document.write("<ul>");
           document.write("<li class='has-sub '><a href='proxy.html'><span>Proxy</span></a>");
            document.write("<ul>");
              document.write("<li><a href='comefattoproxy.html'>Come è fatto?</a></li>");
			  document.write("<li><a href='acosaserveproxy.html'> A cosa serve?</a></li>");
            document.write("</ul>");
         document.write("</li>");
         document.write("<li class='has-sub '><a href='Firewall.html'><span>Firewall</span></a>");
            document.write("<ul>");
               document.write("<li><a href='comefattofirewall.html'><span>Come è fatto?</span></a></li>");
			   document.write("<li><a href='a cosa serve firewall.html'><span>A cosa serve?</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
		    document.write("<li class='has-sub '><a href='Modem.html'><span>Modem</span></a>");
            document.write("<ul>");
               document.write("<li><a href='comefattomodem.html'><span>Come è fatto?</span></a></li>");
			   document.write("<li><a href='acosaservemodem.html'><span>A cosa serve?</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
		 document.write("<li class='has-sub '><a href='Router.html'><span>Router</span></a>");
            document.write("<ul>");
              document.write("<li><a href='comefattorouter.html'>Come è fatto?</a></li>");
			  document.write("<li><a href='acosaserverouter.html'><span>A cosa serve?</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
		 document.write("<li class='has-sub '><a href='Switch.html'><span>Switch</span></a>");
            document.write("<ul>");
              document.write("<li><a href='comefattoswitch.html'>Come è fatto?</a></li>");
			  document.write("<li><a href='acosaserveswitch.html'><span>A cosa serve?</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
		 document.write("<li class='has-sub '><a href='Hub.html'><span>Hub</span></a>");
            document.write("<ul>");
              document.write("<li><a href='comefattohub.html'>Come è fatto?</a></li>");
			  document.write("<li><a href='acosaservehub.html'><span>A cosa serve?</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
      document.write("</ul>");
   document.write("</li>");
   document.write("<li><a href='#'><span>About</span></a></li>");
   document.write("<li><a href='#'><span>Contact</span></a></li>");
document.write("</ul>");
document.write("</div>");