Document.write("<div id='cssmenu'> ");
Document.write("<ul>");
   Document.write("<li><a href="INDEX.html"><span>Home</span></a></li>");
   Document.write("<li class='has-sub '><a href='#'><span>Componenti</span></a>");
    Document.write("<ul>");
        Document.write("<li class='has-sub '><a href="modem.html"><span>Modem</span></a>");
            Document.write("<ul>");
              Document.write("<li><a href="modem serve.html"><span>Modem serve</span></a></li>");
               Document.write("<li><a href='#'><span>Modem fatto</span></a></li>");
            Document.write("</ul>");
         Document.write("</li>");
         Document.write("<li class='has-sub '><a href="proxy.html"><span>Proxy</span></a>");
            Document.write("<ul>");
               Document.write("<li><a href='#'><span>Proxy serve</span></a></li>");
               Document.write("<li><a href='#'><span>Proxy fatto</span></a></li>");

            Document.write("</ul>");
			Document.write("<li class='has-sub '><a href="Firewall.html"><span>Firewall</span></a>");
            Document.write("<ul>");
              Document.write(" <li><a href='#'><span>Firewall serve</span></a></li>");
               Document.write("<li><a href='#'><span>Firewall fatto</span></a></li>");
           Document.write("</ul>");
			Document.write("<li class='has-sub '><a href="Router.html"><span>Router</span></a>");
            Document.write("<ul>");
               Document.write("<li><a href='#'><span>Router serve</span></a></li>");
               Document.write("<li><a href='#'><span>Router fatto</span></a></li>");
			   Document.write("</ul>");
			   
			   Document.write("<li class='has-sub '><a href="Switch.html"><span>Switch</span></a>");
            Document.write("<ul>");
              Document.write("<li><a href='#'><span>Switch serve</span></a></li>");
              Document.write("<li><a href='#'><span>Switch fatto</span></a></li>");
			   Document.write("</ul>");
			   Document.write("<li class='has-sub '><a href="Access Point.html"><span>Access Point</span></a>");
           Document.write("<ul>");
              Document.write("<li><a href='#'><span>Access Point serve</span></a></li>");
               Document.write("<li><a href='#'><span>Access Point fatto</span></a></li>");
            Document.write("</ul>");
         Document.write("</li>");
         Document.write("</li>");
      Document.write("</ul>");
  Document.write("</li>");
   Document.write("<li><a href='#'><span>About</span></a></li>");
   Document.write("<li><a href='#'><span>Contact</span></a></li>");
Document.write("</ul>");
Document.write("</div>");