document.write("<div id='cssmenu'>");
document.write("<ul>");
   document.write("<li class='active'><a href='index.html'><span>Home</span></a></li>");
   document.write("<li class='has-sub last'><a href='#'><span>Componenti</span></a>");
      document.write("<ul>");
         document.write("<li class='has-sub'><a href='modem.html'><span>Modem</span></a>");
            document.write("<ul>");
               document.write("<li><a href='modem.html#fatto'><span>Come è fatto?</span></a></li>");
               document.write("<li class='last'><a href='modem.html#arrivato'><span>A cosa serve?</span></a></li>");
            document.write("</ul>");
			document.write("<li class='has-sub'><a href='router.html'><span>Router</span></a>");
            document.write("<ul>");
               document.write("<li><a href='router.html#fatto'><span>Come è fatto?</span></a></li>");
               document.write("<li class='last'><a href='router.html#arrivato'><span>A cosa serve?</span></a></li>");
            document.write("</ul>");
			document.write("<li class='has-sub'><a href='proxy.html'><span>Proxy</span></a>");
            document.write("<ul>");
               document.write("<li><a href='proxy.html#fatto'><span>Come è fatto?</span></a></li>");
               document.write("<li class='last'><a href='proxy.html#arrivato'><span>A cosa serve?</span></a></li>");
            document.write("</ul>");
			document.write("<li class='has-sub'><a href='switch.html'><span>Switch</span></a>");
            document.write("<ul>");
               document.write("<li><a href='switch.html#fatto'><span>Come è fatto?</span></a></li>");
               document.write("<li class='last'><a href='switch.html#arrivato'><span>A cosa serve?</span></a></li>");
            document.write("</ul>");
        document.write("</li>");
         document.write("<li class='has-sub'><a href='firewall.html'><span>Firewall</span></a>");
            document.write("<ul>");
               document.write("<li><a href='firewall.html#fatto'><span>Come è fatto?</span></a></li>");
               document.write("<li class='last'><a href='firewall.html#arrivato'><span>A cosa serve?</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
		 document.write("<li class='has-sub'><a href='hub.html'><span>Hub</span></a>");
            document.write("<ul>");
               document.write("<li><a href='hub.html#fatto'><span>Come è fatto?</span></a></li>");
               document.write("<li class='last'><a href='hub.html#arrivato'><span>A cosa serve?</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
		 document.write("<li class='has-sub'><a href='accesspoint.html'><span>Access Point</span></a>");
            document.write("<ul>");
               document.write("<li><a href='accesspoint.html#fatto'><span>Come è fatto?</span></a></li>");
               document.write("<li class='last'><a href='accesspoint.html#arrivato'><span>A cosa serve?</span></a></li>");
            document.write("</ul>");
         document.write("</li>");
      document.write("</ul>");
   document.write("</li>");
document.write("</ul>");
document.write("</div>");