document.write("<div id='cssmenu'>");
document.write("<ul>");
document.write("   <li><a href='index.html'><span>Home</span></a></li>");
document.write("   <li class='has-sub '><a href='#'><span>componenti</span></a>");
document.write("      <ul>");
document.write("         <li class='has-sub '><a href='modem.html'><span>modem</span></a>");
document.write("            <ul>");
document.write("               <li><a href='modemcosa.html'><span>cosa fa</span></a></li>");
document.write("            </ul>");
document.write("         </li>");
document.write("         <li class='has-sub '><a href='proxy.html'><span>proxy</span></a>");
document.write("            <ul>");
document.write("               <li><a href='proxycosa.html'><span>cosa fa</span></a></li>");
document.write("            </ul>");
document.write("         </li>");
document.write("           <li class='has-sub '><a href='firewall.html'>firewall<span></span></a>");
document.write("            <ul>");
document.write("			 <li><a href='firewallcosa.html'><span></span>cosa fa </a></li>");
document.write("			 </ul>");
document.write("         </li>");
document.write("         <li class='has-sub '><a href='router.html'><span>router</span></a> ");
document.write("            <ul>");
document.write("               <li><a href='routercosa.html'><span>cosa fa</span></a></li>");
document.write("			    </ul>");
document.write("		    </li>");
document.write("         <li class='has-sub '><a href='access point.html'><span>access point</span></a> ");
document.write("            <ul>");
document.write("               <li><a href='access pointcosa.html'><span>cosa fa</span></a></li>");
document.write("			</ul>");
document.write("		  </li>");
document.write("         <li class='has-sub '><a href='hub.html'><span>hub</span></a> ");
document.write("            <ul>");
document.write("               <li><a href='hubcosa.html'><span>cosa fa</span></a></li>");
document.write("			</ul>");
document.write("		  </li>");
document.write("         <li class='has-sub '><a href='gateway.html'><span>gateway</span></a> ");
document.write("            <ul>");
document.write("               <li><a href='gatewaycosa.html'><span>cosa fa</span></a></li>");
document.write("			</ul>");
document.write("		  </li>");
document.write("         <li class='has-sub '><a href='switch.html'><span>switch</span></a> ");
document.write("            <ul>");
document.write("               <li><a href='switchcosa.html'><span>cosa fa</span></a></li>");
document.write("			</ul>");
document.write("		  </li>");
document.write("            </ul>");
document.write("         </li> ");

document.write("		 ");
document.write("   <li><a href='#'><span>About</span></a></li>");
document.write("   <li><a href='#'><span>Contact</span></a></li>");
document.write("</ul>");
document.write("</div>");